//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharesBrokeringClient.SharesBrokeringWSReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://shares.me.org/", ConfigurationName="SharesBrokeringWSReference.SharesBrokeringWS")]
    public interface SharesBrokeringWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/getUserRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/getUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.getUserResponse getUser(SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/getUserRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/getUserResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getUserResponse> getUserAsync(SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/LoginRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/LoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.LoginResponse Login(SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/LoginRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/LoginResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.LoginResponse> LoginAsync(SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/AddUserShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/AddUserShareResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareResponse AddUserShare(SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/AddUserShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/AddUserShareResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareResponse> AddUserShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/AddShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/AddShareResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.AddShareResponse AddShare(SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/AddShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/AddShareResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddShareResponse> AddShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/ExchangeWalletRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/ExchangeWalletResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletResponse ExchangeWallet(SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/ExchangeWalletRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/ExchangeWalletResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletResponse> ExchangeWalletAsync(SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/getNewsRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/getNewsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.getNewsResponse getNews(SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/getNewsRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/getNewsResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getNewsResponse> getNewsAsync(SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/GetUserSharesRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/GetUserSharesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesResponse GetUserShares(SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/GetUserSharesRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/GetUserSharesResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesResponse> GetUserSharesAsync(SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/SellShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/SellShareResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.SellShareResponse SellShare(SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/SellShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/SellShareResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.SellShareResponse> SellShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/getShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/getShareResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.getShareResponse getShare(SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/getShareRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/getShareResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getShareResponse> getShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/GetCurrencyListRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/GetCurrencyListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListResponse GetCurrencyList(SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/GetCurrencyListRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/GetCurrencyListResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListResponse> GetCurrencyListAsync(SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/adjustWalletRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/adjustWalletResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletResponse adjustWallet(SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/adjustWalletRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/adjustWalletResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletResponse> adjustWalletAsync(SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/AddNewUserRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/AddNewUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserResponse AddNewUser(SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/AddNewUserRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/AddNewUserResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserResponse> AddNewUserAsync(SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/GetFilteredSharesRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/GetFilteredSharesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesResponse GetFilteredShares(SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shares.me.org/SharesBrokeringWS/GetFilteredSharesRequest", ReplyAction="http://shares.me.org/SharesBrokeringWS/GetFilteredSharesResponse")]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesResponse> GetFilteredSharesAsync(SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.netbeans.org/schema/Users")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string currencyField;
        
        private double walletField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Wallet {
            get {
                return this.walletField;
            }
            set {
                this.walletField = value;
                this.RaisePropertyChanged("Wallet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.netbeans.org/schema/Shares")]
    public partial class SharePrice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string currencyField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.netbeans.org/schema/Shares")]
    public partial class Share : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyNameField;
        
        private string companySymbolField;
        
        private int qtyAvailableField;
        
        private SharePrice priceField;
        
        private System.DateTime updateDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanySymbol {
            get {
                return this.companySymbolField;
            }
            set {
                this.companySymbolField = value;
                this.RaisePropertyChanged("CompanySymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int QtyAvailable {
            get {
                return this.qtyAvailableField;
            }
            set {
                this.qtyAvailableField = value;
                this.RaisePropertyChanged("QtyAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SharePrice Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
                this.RaisePropertyChanged("UpdateDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.netbeans.org/schema/UserShares")]
    public partial class ShareInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companySymbolField;
        
        private int quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanySymbol {
            get {
                return this.companySymbolField;
            }
            set {
                this.companySymbolField = value;
                this.RaisePropertyChanged("CompanySymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getUserRequest() {
        }
        
        public getUserRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SharesBrokeringClient.SharesBrokeringWSReference.user @return;
        
        public getUserResponse() {
        }
        
        public getUserResponse(SharesBrokeringClient.SharesBrokeringWSReference.user @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public LoginResponse() {
        }
        
        public LoginResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserShare", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class AddUserShareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg3;
        
        public AddUserShareRequest() {
        }
        
        public AddUserShareRequest(string arg0, string arg1, int arg2, double arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserShareResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class AddUserShareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AddUserShareResponse() {
        }
        
        public AddUserShareResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddShare", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class AddShareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg4;
        
        public AddShareRequest() {
        }
        
        public AddShareRequest(string arg0, string arg1, int arg2, string arg3, double arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddShareResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class AddShareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AddShareResponse() {
        }
        
        public AddShareResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExchangeWallet", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class ExchangeWalletRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public ExchangeWalletRequest() {
        }
        
        public ExchangeWalletRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExchangeWalletResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class ExchangeWalletResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ExchangeWalletResponse() {
        }
        
        public ExchangeWalletResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNews", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class getNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getNewsRequest() {
        }
        
        public getNewsRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewsResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class getNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getNewsResponse() {
        }
        
        public getNewsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserShares", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class GetUserSharesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        public GetUserSharesRequest() {
        }
        
        public GetUserSharesRequest(string arg0, string arg1, int arg2, int arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserSharesResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class GetUserSharesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SharesBrokeringClient.SharesBrokeringWSReference.ShareInfo[] @return;
        
        public GetUserSharesResponse() {
        }
        
        public GetUserSharesResponse(SharesBrokeringClient.SharesBrokeringWSReference.ShareInfo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SellShare", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class SellShareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg3;
        
        public SellShareRequest() {
        }
        
        public SellShareRequest(string arg0, string arg1, int arg2, double arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SellShareResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class SellShareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public SellShareResponse() {
        }
        
        public SellShareResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getShare", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class getShareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getShareRequest() {
        }
        
        public getShareRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getShareResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class getShareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SharesBrokeringClient.SharesBrokeringWSReference.Share @return;
        
        public getShareResponse() {
        }
        
        public getShareResponse(SharesBrokeringClient.SharesBrokeringWSReference.Share @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrencyList", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class GetCurrencyListRequest {
        
        public GetCurrencyListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrencyListResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class GetCurrencyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public GetCurrencyListResponse() {
        }
        
        public GetCurrencyListResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="adjustWallet", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class adjustWalletRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg2;
        
        public adjustWalletRequest() {
        }
        
        public adjustWalletRequest(string arg0, double arg1, bool arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="adjustWalletResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class adjustWalletResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public adjustWalletResponse() {
        }
        
        public adjustWalletResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewUser", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class AddNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg3;
        
        public AddNewUserRequest() {
        }
        
        public AddNewUserRequest(string arg0, string arg1, string arg2, double arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewUserResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class AddNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AddNewUserResponse() {
        }
        
        public AddNewUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilteredShares", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class GetFilteredSharesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        public GetFilteredSharesRequest() {
        }
        
        public GetFilteredSharesRequest(string arg0, string arg1, int arg2, int arg3, double arg4, double arg5, string arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilteredSharesResponse", WrapperNamespace="http://shares.me.org/", IsWrapped=true)]
    public partial class GetFilteredSharesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://shares.me.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SharesBrokeringClient.SharesBrokeringWSReference.Share[] @return;
        
        public GetFilteredSharesResponse() {
        }
        
        public GetFilteredSharesResponse(SharesBrokeringClient.SharesBrokeringWSReference.Share[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SharesBrokeringWSChannel : SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SharesBrokeringWSClient : System.ServiceModel.ClientBase<SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS>, SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS {
        
        public SharesBrokeringWSClient() {
        }
        
        public SharesBrokeringWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SharesBrokeringWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharesBrokeringWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharesBrokeringWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.getUserResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.getUser(SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public SharesBrokeringClient.SharesBrokeringWSReference.user getUser(string arg0) {
            SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest();
            inValue.arg0 = arg0;
            SharesBrokeringClient.SharesBrokeringWSReference.getUserResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).getUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getUserResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.getUserAsync(SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest request) {
            return base.Channel.getUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getUserResponse> getUserAsync(string arg0) {
            SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.getUserRequest();
            inValue.arg0 = arg0;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).getUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.LoginResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.Login(SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string arg0, string arg1) {
            SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SharesBrokeringClient.SharesBrokeringWSReference.LoginResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).Login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.LoginResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.LoginAsync(SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.LoginResponse> LoginAsync(string arg0, string arg1) {
            SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.LoginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.AddUserShare(SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest request) {
            return base.Channel.AddUserShare(request);
        }
        
        public bool AddUserShare(string arg0, string arg1, int arg2, double arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).AddUserShare(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.AddUserShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest request) {
            return base.Channel.AddUserShareAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareResponse> AddUserShareAsync(string arg0, string arg1, int arg2, double arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.AddUserShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).AddUserShareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.AddShareResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.AddShare(SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest request) {
            return base.Channel.AddShare(request);
        }
        
        public bool AddShare(string arg0, string arg1, int arg2, string arg3, double arg4) {
            SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            SharesBrokeringClient.SharesBrokeringWSReference.AddShareResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).AddShare(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddShareResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.AddShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest request) {
            return base.Channel.AddShareAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddShareResponse> AddShareAsync(string arg0, string arg1, int arg2, string arg3, double arg4) {
            SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.AddShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).AddShareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.ExchangeWallet(SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest request) {
            return base.Channel.ExchangeWallet(request);
        }
        
        public bool ExchangeWallet(string arg0, string arg1) {
            SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).ExchangeWallet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.ExchangeWalletAsync(SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest request) {
            return base.Channel.ExchangeWalletAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletResponse> ExchangeWalletAsync(string arg0, string arg1) {
            SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.ExchangeWalletRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).ExchangeWalletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.getNewsResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.getNews(SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest request) {
            return base.Channel.getNews(request);
        }
        
        public string getNews(string arg0) {
            SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest();
            inValue.arg0 = arg0;
            SharesBrokeringClient.SharesBrokeringWSReference.getNewsResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).getNews(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getNewsResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.getNewsAsync(SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest request) {
            return base.Channel.getNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getNewsResponse> getNewsAsync(string arg0) {
            SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.getNewsRequest();
            inValue.arg0 = arg0;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).getNewsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.GetUserShares(SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest request) {
            return base.Channel.GetUserShares(request);
        }
        
        public SharesBrokeringClient.SharesBrokeringWSReference.ShareInfo[] GetUserShares(string arg0, string arg1, int arg2, int arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).GetUserShares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.GetUserSharesAsync(SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest request) {
            return base.Channel.GetUserSharesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesResponse> GetUserSharesAsync(string arg0, string arg1, int arg2, int arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.GetUserSharesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).GetUserSharesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.SellShareResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.SellShare(SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest request) {
            return base.Channel.SellShare(request);
        }
        
        public bool SellShare(string arg0, string arg1, int arg2, double arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            SharesBrokeringClient.SharesBrokeringWSReference.SellShareResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).SellShare(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.SellShareResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.SellShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest request) {
            return base.Channel.SellShareAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.SellShareResponse> SellShareAsync(string arg0, string arg1, int arg2, double arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.SellShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).SellShareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.getShareResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.getShare(SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest request) {
            return base.Channel.getShare(request);
        }
        
        public SharesBrokeringClient.SharesBrokeringWSReference.Share getShare(string arg0, string arg1) {
            SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SharesBrokeringClient.SharesBrokeringWSReference.getShareResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).getShare(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getShareResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.getShareAsync(SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest request) {
            return base.Channel.getShareAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.getShareResponse> getShareAsync(string arg0, string arg1) {
            SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.getShareRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).getShareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.GetCurrencyList(SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest request) {
            return base.Channel.GetCurrencyList(request);
        }
        
        public string[] GetCurrencyList() {
            SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest();
            SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).GetCurrencyList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.GetCurrencyListAsync(SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest request) {
            return base.Channel.GetCurrencyListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListResponse> GetCurrencyListAsync() {
            SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.GetCurrencyListRequest();
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).GetCurrencyListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.adjustWallet(SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest request) {
            return base.Channel.adjustWallet(request);
        }
        
        public bool adjustWallet(string arg0, double arg1, bool arg2) {
            SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).adjustWallet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.adjustWalletAsync(SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest request) {
            return base.Channel.adjustWalletAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletResponse> adjustWalletAsync(string arg0, double arg1, bool arg2) {
            SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.adjustWalletRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).adjustWalletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.AddNewUser(SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest request) {
            return base.Channel.AddNewUser(request);
        }
        
        public bool AddNewUser(string arg0, string arg1, string arg2, double arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).AddNewUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.AddNewUserAsync(SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest request) {
            return base.Channel.AddNewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserResponse> AddNewUserAsync(string arg0, string arg1, string arg2, double arg3) {
            SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.AddNewUserRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).AddNewUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesResponse SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.GetFilteredShares(SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest request) {
            return base.Channel.GetFilteredShares(request);
        }
        
        public SharesBrokeringClient.SharesBrokeringWSReference.Share[] GetFilteredShares(string arg0, string arg1, int arg2, int arg3, double arg4, double arg5, string arg6) {
            SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesResponse retVal = ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).GetFilteredShares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesResponse> SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS.GetFilteredSharesAsync(SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest request) {
            return base.Channel.GetFilteredSharesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesResponse> GetFilteredSharesAsync(string arg0, string arg1, int arg2, int arg3, double arg4, double arg5, string arg6) {
            SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest inValue = new SharesBrokeringClient.SharesBrokeringWSReference.GetFilteredSharesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            return ((SharesBrokeringClient.SharesBrokeringWSReference.SharesBrokeringWS)(this)).GetFilteredSharesAsync(inValue);
        }
    }
}
